### DISCUSSION TITLE
false positive? excessive-permissions on a reusable workflow with perms defined in parent caller.

### DISCUSSION THREAD

**Discussion by userdocs** [zizmorcore/zizmor#471] [Q&A] [answered]
with zizmor 1.2.1 i am seeing this warning

```shell
[src\registry.rs:102:63] pfx = "."
warning[excessive-permissions]: overly broad permissions
   --> .github/workflows\ci-alpine-release.yml:12:3
    |
 12 | /   release:
 13 | |     runs-on: ubuntu-24.04
...   |
108 | |           allowUpdates: true
109 | |           token: "${{ github.TOKEN }}"
    | |                                       -
    | |_______________________________________|
    |                                         this job
    |                                         default permissions used due to no permissions: block
    |
    = note: audit confidence → Medium
```

From this warning https://woodruffw.github.io/zizmor/audits/#excessive-permissions

But this is a reusable workflow. My permissions are defined in the parent calling it.

```yaml
  ci-alpine-release:
    needs: [ci-alpine-build]
    if: always() && github.event.inputs.release == 'true' && contains(needs.*.result, 'success') && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    concurrency:
      group: ci-alpine-release
      cancel-in-progress: true
    permissions:
      contents: write
    uses: ./.github/workflows/ci-alpine-release.yml
    with:
      distinct_id: ${{ github.event.inputs.distinct_id }}
```

I think this is a false positive?
