### DISCUSSION TITLE
Template injection remediation when used as an action input

### DISCUSSION THREAD

**Discussion by chgl** [zizmorcore/zizmor#890] [Q&A] [answered]
As of v1.9.0, the template-injection audit also triggers if an expandable variable is passed to another GitHub action as input.

For example, a reusable workflow provides `build-context` as an input string and passes it to the docker/build-push action:

```yaml
      - name: test
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.build-context }}
```

(Taken from https://github.com/chgl/.github/blob/master/.github/workflows/standard-build.yaml#L178-L192).

Zizmor now remarks:

```console
note[template-injection]: code injection via template expansion
   --> ./.github/workflows/standard-build.yaml:178:9
    |
178 |       - name: Build unit test image layer
    |         --------------------------------- note: this step
179 |         if: ${{ inputs.enable-build-test-layer == true }}
...
182 |         with:
183 |           context: ${{ inputs.build-context }}
    |           ------------------------------------ note: ${{ inputs.build-context }} may expand into attacker-controllable code
    |
    = note: audit confidence → Unknown
```

Is there any way to handle such cases? Or even ignore them explicitly?

**Comment by woodruffw** [comment]
Hey @chgl, thanks for opening a discussion.

> As of v1.9.0, the template-injection audit also triggers if an expandable variable is passed to another GitHub action as input.

To qualify: `zizmor` doesn't flag _every_ input, just ones that it thinks correspond to injectable code. In this particular case, `docker/build-push-action`'s `context:` input is one that `zizmor` thinks is code-injectable, per our extraction of GitHub's CodeQL sinks:

https://github.com/zizmorcore/zizmor/blob/45be0d61bd6bd1517ef116a43afc7824aec7cdb2/crates/zizmor/data/codeql-injection-sinks.json#L9-L13

That in turn was derived from CodeQL's model here:

https://github.com/github/codeql/blob/fcf6c3c4e83f127aea9ce5aed3e0ceb4feb65bc5/actions/ql/lib/ext/manual/docker_build-push-action.model.yml

However, from a look, I'm not 100% clear on _why_ CodeQL thinks that this input is a code injection source -- `context` appears to influence some flags, but doesn't inject code directly. So this _might_ be an upstream false positive from CodeQL's data.

TL;DR: This _might_ be an upstream bug in CodeQL's data, which I'll be looking into. However, in the mean time, you could also manually ignore this with a `# zizmor: ignore[template-injection]` comment, e.g.:

```yaml
      - name: test
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ inputs.build-context }} # zizmor: ignore[template-injection]
```

**Reply by woodruffw** [reply]
From looking a bit more: `inputs.context` can include a [Handlebars expression](https://handlebarsjs.com/guide/), and those might be susceptible to code injection. So I wonder if that's why CodeQL has it manually marked.

**Reply by woodruffw** [reply]
For example: https://mahmoudsec.blogspot.com/2019/04/handlebars-template-injection-and-rce.html

**Reply by woodruffw** [reply, marked as answer]
Given the above, I _think_ this is a true positive, albeit a confusing one (since the code execution in question is via a handlebars expression).

**Reply by chgl** [reply]
Thank you for the detailed explanation!

 Is there any reasonable remediation for this? Something like running a script to first sanitize all input and then pass it to the action is the only idea I have... which seems quite involved.

**Reply by woodruffw** [reply]
Yeah, unfortunately this seems non-trivial to remediate 😞 -- an ignore comment _might_ be right if you're confident that only you (or other privileged actors) can set the `inputs.context` field. Sanitizing would probably be the most appropriate general solution, but I agree about that being involved (and probably _too_ involved to justify for a single input).

It might not be practical for them to change either, but ideally `docker/build-push-action` wouldn't use a full-fledged Handlebars expression here -- they could _probably_ get away with a Mustache template instead, which wouldn't include the arbitrary code execution. But even that would be quite a long migration tail.

TL;DR: There unfortunately may not be a great general remediation for this that is also not exceedingly complex -- your best bet may be ignoring it.

**Reply by chgl** [reply]
Thanks again! Ignoring does seem like the best bet for now - still it's incredibly useful to at least know where to be cautious when passing inputs.

**Reply by mschoettle** [reply]
I actually ran into the same exact use case and tried to fix it via `env` as usual:

```yaml
- name: Build and push Docker image
   id: push
   uses: docker/build-push-action@v6.18.0
   env:
     CONTEXT: ${{ inputs.context }}
   with:
     context: ${{ env.CONTEXT }}
```

But it still gets flagged. Should this not fix it or is it still susceptible to the above mentioned code executed via handlebar expressions?
