### ISSUE TITLE
Develop a `zizmor` GitHub Action

### ISSUE THREAD

**Issue by ncoghlan** [zizmorcore/zizmor#69]
It would be handy if https://github.com/woodruffw/zizmor?tab=readme-ov-file#use-in-github-actions linked to a GitHub action in this repo which ran zizmor over the repo whenever any of the files in the workflow folder changed.

In the meantime, I'll submit a PR with a direct link to the upload-sarif example at https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-that-runs-the-eslint-analysis-tool

**Comment by ncoghlan** [comment]
First draft of such a workflow (based on the ESLint one):

```
name: "Scan workflows"

on:
    pull_request:
      branches:
        - "**"
      paths:
        # Run for changes to *any* workflow file
        - ".github/workflows/docs.yml"
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install zizmor
        run: cargo install zizmor

      - name: Scan workflows
        run:
          zizmor --format=sarif . | tee workflow-scan.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: workflow-scan.sarif
```

**Comment by ncoghlan** [comment]
Also see https://github.com/woodruffw/zizmor/pull/71

**Comment by woodruffw** [comment]
Thanks for the issue @ncoghlan! Completely agreed -- ideally there'd be an action hosted within this repo itself so people could do:

```yaml
- uses: woodruffw/zizmor/action@tag
  with: ...
```

...and get SARIF, etc. integration right out of the box :slightly_smiling_face:

**Comment by woodruffw** [comment]
Related request: https://github.com/woodruffw/zizmor/issues/89.

**Comment by woodruffw** [comment]
Leaving this open since I still want to build a full-fledged action for zizmor, but the docs now include an example annotated workflow based on the one @ncoghlan contributed!

<img width="779" alt="Screenshot 2024-11-01 at 10 36 20 AM" src="https://github.com/user-attachments/assets/98884da9-a17b-4c42-b30a-82dbfe3352eb">

**Comment by tobiastornros** [comment]
Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.

**Comment by colindean** [comment]
> Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.

What does a user see when they cannot use code scanning but try to use the tools that upload the SARIF file to GH?

**Comment by tobiastornros** [comment]
> > Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.
> 
> What does a user see when they cannot use code scanning but try to use the tools that upload the SARIF file to GH?

<img width="638" alt="image" src="https://github.com/user-attachments/assets/9770aa1d-4594-49da-b037-0fb0620e8ada">

**Comment by daviddavis** [comment]
For us, we'd like to have an action that will simply fail PRs, etc if there are security issues. So maybe having two Actions or two "modes" makes sense: one to perform code scanning and one to gate changes.

**Comment by woodruffw** [comment]
> For us, we'd like to have an action that will simply fail PRs, etc if there are security issues. So maybe having two Actions or two "modes" makes sense: one to perform code scanning and one to gate changes.

I believe you can configure this with GitHub's advanced security feature: you can set a required check for no alerts raised by all security tools, or by a specific tool like `zizmor`.

(With that being said, this is what the standalone action will do -- it'll optionally integrate with advanced security via SARIF, but by default it'll just spit out a render and fail if there are any errors.)

**Comment by woodruffw** [comment]
> Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.

@tobiastornros would you be interested in sending a PR adding that as a note to the docs? I'd greatly appreciate it!

**Comment by tobiastornros** [comment]
> > Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.
> 
> @tobiastornros would you be interested in sending a PR adding that as a note to the docs? I'd greatly appreciate it!

Done. See #121

**Comment by jazmon** [comment]
I've tried out the example but the compilation of zizmor is slow and it would be nice to have it precompiled.


In lieu of the security checks (which are an additional cost on enterprise cloud too) you can use a custom matcher and get the info as annotations

My workflow's steps:

```yml
- uses: actions/checkout@v4
  with:
    ref: ${{ github.sha }}
    # optimize fetching for big repos
    sparse-checkout: |
      .github/actions
      .github/workflows
      .github/zizmor-matcher.json
      zizmor.yml
      requirements.txt

- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.12'
    cache: 'pip'

- name: Install requirements
  run: pip install -r requirements.txt

- name: Run Zizmor checks
  env:
    # need more wide permissions to look up shared actions from other repos
    GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  run: |
    echo "::add-matcher::.github/zizmor-matcher.json"
    zizmor --format plain ${{ github.workspace }}
```

With my `zizmor-matcher.json`

```json
{
  "problemMatcher": [
    {
      "owner": "zizmor-error",
      "severity": "error",
      "pattern": [
        {
          "regexp": "^error\\[([\\w-]+)\\]: (.+)$",
          "code": 1,
          "message": 2
        },
        {
          "regexp": "^\\s+-->\\s+(.+):(\\d+):(\\d+)",
          "file": 1,
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "owner": "zizmor-warning",
      "severity": "warning",
      "pattern": [
        {
          "regexp": "^warning\\[([\\w-]+)\\]: (.+)$",
          "code": 1,
          "message": 2
        },
        {
          "regexp": "^\\s+-->\\s+(.+):(\\d+):(\\d+)",
          "file": 1,
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by woodruffw** [comment]
Thanks for sharing your matcher! I didn't know about that GHA feature.

> I've tried out the example but the compilation of zizmor is slow and it would be nice to have it precompiled.

FWIW, the example was updated recently to use `uvx`, which installs a pre-compiled version. That should make installations nearly instantaneous:

https://woodruffw.github.io/zizmor/usage/#use-in-github-actions

**Comment by mattdowdell** [comment]
It's a little bare bones, but I was able to use the new zizmor container to make a docker-based action. sharing in case folks find it useful:

<details>
<summary><code>.github/actions/zizmor/action.yml</code></summary>

```yaml
name: Zizmor
description: Static analysis for GitHub Actions.

inputs:
  inputs:
    description: The inputs to audit.
    required: true
  persona:
    description: The persona to use while auditing.
    default: regular
    required: false
  github_token:
    description: The GitHub API token to use.
    default: ${{ github.token }}
    required: false
  format:
    description: The output format to emit.
    default: plain
    required: false
  min_severity:
    description: Filter all results below this severity
    default: 'unknown'
    required: false
  min_confidence:
    description: Filter all results below this confidence
    default: 'unknown'
    required: false
  collect:
    description: Control which kinds of inputs are collected for auditing.
    default: 'all'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
```
</details>

<details>
<summary><code>.github/actions/zizmor/Dockerfile</code></summary>

```dockerfile
FROM ghcr.io/woodruffw/zizmor:1.4.1@sha256:dbd8fffd06c51b0ea80dff6115547a0b4fe97fc67785d82f198ecf36d8a32ebe

COPY --chmod=555 entrypoint.sh /

RUN useradd --create-home zizmor
USER zizmor

ENTRYPOINT ["/entrypoint.sh"]
```
</details>

<details>
<summary><code>.github/actions/zizmor/entrypoint.yaml</code></summary>

```sh
#!/bin/bash

set -euo pipefail

export GH_TOKEN="${INPUT_GITHUB_TOKEN}"

/app/zizmor \
	--cache-dir /home/zizmor/.cache/zizmor \
	--persona "${INPUT_PERSONA:-regular}" \
	--format "${INPUT_FORMAT:-plain}" \
	--min-severity "${INPUT_MIN_SEVERITY:-unknown}" \
	--min-confidence "${INPUT_MIN_CONFIDENCE:-unknown}" \
	--collect "${INPUT_COLLECT:-all}" \
	${INPUT_INPUTS[@]}
```
</details>

<details>
<summary>Usage</summary>

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    with:
      persist-credentials: false

  - name: Run zizmor
    uses: ./.github/actions/zizmor
    with:
      persona: pedantic
      inputs: .github/actions/*/*.yml .github/workflows/*.yml
```

A few notes for anyone looking to build upon it:

- I created a user to run `zizmor` under, mostly because I also run `trivy` in CI and the lack of user triggered [AVD-DS-0002](https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0002/).
- `$HOME` gets overridden when running the image, necessitating the override to the default cache dir location. Otherwise it goes in `/github/home/.cache/zizmor` which didn't exist. You could use that for the home dir when calling `useradd`, but that might be brittle if used on self-hosted runners (I don't know for sure), so this felt like the safer option.
- I set what I assumed were the de facto defaults for min severity/confidence, although the CLI didn't document a default for these options.
- I neglected to deal with options that couldn't have a default like --config. I didn't have a config file, so it was an acceptable omission. I also didn't deal with boolean options like --no-config, --quiet, etc.
- To make building the action easier, it might be useful to accept environment variables for all options prefixed with INPUT, e.g. INPUT_CONFIG. With that, you might be able to drop the `entrypoint.sh` altogether.
- The parsing of inputs was a little tricky to get around. I wanted to accept multiple paths at once, but GitHub Actions doesn't have a concept of arrays. It might make life a little easier if some post-precessing were performed on the CLI arguments to split paths. right now, if they're in any way joined, you get the slightly confusing error "error: invalid GitHub repository reference".

**Comment by polarathene** [comment]
As someone not familiar with the container action support, I was a bit unsure what the story was with volume mount and workdir, but I see that [GHA mounts the runner workspace path and sets that as the workdir](https://docs.github.com/en/actions/sharing-automations/creating-actions/dockerfile-support-for-github-actions#workdir).

Do note the [docs advice on `USER`](https://docs.github.com/en/actions/sharing-automations/creating-actions/dockerfile-support-for-github-actions#user):

> _Docker actions must be run by the default Docker user (`root`). Do not use the `USER` instruction in your `Dockerfile`, because you won't be able to access the `GITHUB_WORKSPACE` directory._

So despite the `trivy` concern, it does go against what GHA expects. Probably only an issue should you want to write anything to the volume mount.

**For reference:** Unless using `--init` or providing an init command as the entrypoint like `tini`, I have observed that for non-root users that so long as `+x` is set (_user/group/other, doesn't actually matter which but must be at least one_), it'll also run the entrypoint script fine. The `root` user will execute the entrypoint regardless of an executable bit. Keeping the `--chmod=555` is probably worthwhile though, and I have no idea if the behaviour differs on other container platforms like Podman or Kubernetes.

---

You could also just run the container directly via a shell `run` command if the action isn't providing much more convenience? 🤔 (_more control that way_)

---

> * but that might be brittle if used on self-hosted runners (I don't know for sure), so this felt like the safer option.

`XDG_CACHE_HOME` could be used with that user location set as default. Then anyone who sets that ENV could point to a different location (_or directly mount the default location_).

---

> * I neglected to deal with options that couldn't have a default like --config. I didn't have a config file, so it was an acceptable omission. I also didn't deal with boolean options like --no-config, --quiet, etc.

A common way to deal with such is to leverage `CMD` with the `ENTRYPOINT`. For GHA that would be via `runs.args`:

- https://docs.github.com/en/actions/sharing-automations/creating-actions/dockerfile-support-for-github-actions#cmd
- https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsargs

---

> `set -euo pipefail`

You have no unbound variables or pipes, but I guess it's just a precaution should the entrypoint be modified in future?

> `/app/zizmor ...`

You should consider using `exec /app/zizmor` to make it PID 1, rather than keeping bash open after calling `zizmor`. It's not likely relevant in this context, but you would do this to properly forward signals usually as otherwise for a longer running process bash could receive SIGTERM/SIGINT from the host, but not respond to it, whereas if you use `exec` it'd have sent the signals to `zizmor` instead.

---

> * The parsing of inputs was a little tricky to get around. I wanted to accept multiple paths at once, but GitHub Actions doesn't have a concept of arrays. It might make life a little easier if some post-precessing were performed on the CLI arguments to split paths. right now, if they're in any way joined, you get the slightly confusing error "error: invalid GitHub repository reference".

You could handle this at the entrypoint, by bundling in some small executable. `jaq` for example could take in a stringified JSON object/array and format that as you'd like, you could also use `tr` within the image already I think to split a string by a delimiter like `,`.

Granted, that still leaves room for user error without a proper array data type as an input though.

**Comment by mattdowdell** [comment]
@polarathene Thanks all great feedback - I've made some updates accordingly.

>> I neglected to deal with options that couldn't have a default like --config. I didn't have a config file, so it was an acceptable omission. I also didn't deal with boolean options like --no-config, --quiet, etc.
>
> A common way to deal with such is to leverage CMD with the ENTRYPOINT. For GHA that would be via runs.args:

I switched to runs.args, but couldn't see a way to conditionally set arguments. I imagine you were suggesting something like trivy-actions used to, e.g. [args](https://github.com/aquasecurity/trivy-action/blob/1b8b83dcc27a38f7d5506919fcea6945aa29b3b8/action.yaml#L104-L129) and [entrypoint](https://github.com/aquasecurity/trivy-action/blob/1b8b83dcc27a38f7d5506919fcea6945aa29b3b8/entrypoint.sh)? I don't have a strong need for all the options, so it's currently an acceptable oversight for me. But full option support using args/entrypoint (or an alternative) would doubtless be needed by someone eventually.

**Comment by polarathene** [comment]
The action you referenced is using `runs.args` to specify default `args` that are array "exec" form to provide as `CMD` for the entrypoint I think?

- `runs.args` for [container action default `CMD`](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsargs)
- `<step>.with.args` for user provided args to the [container action command](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswithargs)

---

## Calling the docker action from a workflow with `with.args`

You'd have to double-check to verify as I haven't played with container actions myself. I do know there's a difference (_I [documented this](https://github.com/docker/compose/issues/12403#issuecomment-2597237191)_) in `Dockerfile` `CMD` instruction and running a container (_from CLI or `compose.yaml`_) with a user provided command to replace the default `CMD`.

In this case, the user can only provide a string value for `with.args`, you should be fine with just providing the args and they'll be split at white-space (_quote wrapping should preserve the white-space when important as documented in my reference link_).

Thus this presumably works for someone using your action:

```yaml
# ...
steps:
  - name: Run zizmor
    uses: ./.github/actions/zizmor
    with:
      # YAML multi-line string using `>-` syntax, allows for a readable set of args:
      # `>` => "Replace newlines with spaces (folded)" + `-` => "No newline at end (strip)"
      # https://yaml-multiline.info/
      args: >-
        --gh-token ${{ secrets.GITHUB_TOKEN }}
        --no-online-audits
        --format json
        --collect all
        --min-severity medium
        --min-confidence medium
```

---

**NOTE:** The [images currently published](https://github.com/woodruffw/zizmor/pkgs/container/zizmor) aren't as flexible with tags, they need to pin the specific release, as they don't provide only `major` or `major.minor` variants. That should probably be supported (_that can get a little complicated though if there's updates to earlier releases, like a patch version bump_).

---

> But full option support using args/entrypoint (or an alternative) would doubtless be needed by someone eventually.

Hopefully the above example shows that probably isn't necessary?

**Comment by polarathene** [comment]
## Alternative examples

The docker action above is similar to using a container directly via [`<step>.run`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun), except to split args to multiple lines you'd tack on a `\` to the end of each line (except the last), or specify a bash array earlier and expand that..

The YAML approach above is a little nicer in that regard (_just be mindful of indentation extra newlines [introducing line breaks that aren't folded](https://github.com/orgs/community/discussions/26105#discussioncomment-3250413)_).

Bash arrays also allow for inline comments between args but the YAML approach does not:

```bash
ARGS=(
  # Args from internal action `runs.args`
  # or users overrides via using `with.args` on the action
  $@
  # Action `inputs.inputs` is always appended:
  ${INPUT_INPUTS[@]}
)

echo "Running command: `zizmor ${ARGS[@]}`"
exec /app/zizmor ${ARGS[@]}
```

As you can see, your current iteration would not allow for overriding via `with.args` and providing specific values that doesn't include the default `inputs.inputs` workspace, so the user would need to be mindful of that fallback/usage if they were to prefer using `with.args` instead of individual `inputs` (_at which point are those providing much value to the user of the action vs CLI args directly like I've shown?_)

With a container action, you can also make it a bit more [useful by setting outputs](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#writing-the-action-code) in the entrypoint script. This would mean not using `exec`, as anything after that in the script would never run otherwise, so perhaps `exec` isn't important for CI use here 😅 

Alternatively if it's just file output, it may be more useful to [just reference the filename written to the volume mount](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action#accessing-files-created-by-a-container-action) instead, separate to your action itself.

---

### Docker via CLI manually (no action)

BTW, this is the `<step>.run` equivalent:

```yaml
# ...
steps:
  - name: 'Run zizmor'
    # This will receive the same exit codes that zizmor returns if there's any errors:
    # https://woodruffw.github.io/zizmor/usage/#exit-codes
    run: |
      docker run --rm \
        --volume ./:/gh-workspace \
        --workdir /gh-workspace \
        ghcr.io/woodruffw/zizmor:1.4.1 \
          --gh-token ${{ secrets.GITHUB_TOKEN }} \
          --no-online-audits \
          --format json \
          --collect all \
          --min-severity medium \
          --min-confidence medium
          ./
```

So that's the kinda difference to keep in mind.
- Is an action useful if I'd be doing effectively the same verbosity and maintenance without additional convenience?
- Is the conveniences like defaults provided worthwhile? (_in the case of a local action you're just shifting some noise away for a single usage in the project, but at least you're still in control of the image tag not falling out of date_)

As an official action, it'd minimize the verbosity a bit, no knowledge of docker required, just the CLI args from the zizmor docs for `with.args: >-`, and the action providing some guidance on `>-` usage with YAML to warn about when it won't fold to a single line.

I'm not sure if you can expect `--format sarif > results.sarif` to work as part of `with.args` though, entrypoint might need to handle that.

---

### Reusable action

Then there's the [current docs guidance/example](https://woodruffw.github.io/zizmor/usage/#use-in-github-actions), which you can adapt into a [reusable workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows):

**`.github/workflows/use-zizmor.yml`:**

```yaml
# This name only appears on the Actions tab of the repo hosting it:
name: 'GitHub Actions Security Analysis with zizmor 🌈'

on:
  workflow_call:
    inputs:
      scan-targets:
        description: 'Zizmor inputs to scan'
        required: false
        type: string
        default: .

      options:
        description: 'Options for zizmor (format is always sarif)'
        required: false
        type: string

# The calling workflow must grant at least these permissions:
permissions:
  security-events: write
  # Required for workflows in private repositories:
  contents: read
  actions: read

jobs:
  zizmor:
    # This name will appear on the workflow run:
    name: 'zizmor (latest release via PyPI)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Install the latest version of uv'
        uses: astral-sh/setup-uv@v5

      - name: 'Run zizmor 🌈'
        run: >-
          uvx zizmor ${{ inputs.options }}
          --format sarif
          ${{ inputs.scan-targets }}
          > results.sarif
        # Reusable workflows have an exception for this secret being implicit:
        # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#overview
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload SARIF file'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor
```

**`.github/workflows/security.yml`:**

```yaml
name: 'Security'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  zizmor:
    name: 'Analyze CI with zizmor'
    # NOTE: Even if you had this workflow referenced locally instead,
    # avoid file path and prefer the repo + ref syntax to ensure
    # all branches get any updates to the workflow synced:
    uses: woodruffw/zizmor/.github/workflows/use-zizmor.yml@main
    with:
      options: >-
        --no-online-audits
        --collect all
        --min-severity medium
        --min-confidence medium
    permissions:
      security-events: write
      # Required for workflows in private repositories:
      contents: read
      actions: read
```

If you want that to instead be treated as an individual step in a job, like a published action, then you would prefer something like a [composite action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action) which [differs a little bit](https://docs.github.com/en/actions/sharing-automations/avoiding-duplication#key-differences-between-reusable-workflows-and-composite-actions), such as `secrets.GITHUB_TOKEN` => `github.token` and no ability to specify required `permissions` (_non-issue when action is documented_). As a job step instead, you may expect the checkout to be separate, or could have inputs for conditionally running the checkout and upload steps.

**Comment by crazy-max** [comment]
> Please note that code scanning is only available for public repositories or for organizations with GitHub Enterprise Cloud.

You could check if Advanced Security is enabled using something like https://github.com/docker/octoguard/blob/834294f1c37ea0d5fd2fa39d06e081d2812a2aae/.github/workflows/zizmor.yml#L44-L51

**Comment by jsoref** [comment]
Fwiw, in check-spelling, I use: https://github.com/check-spelling/check-spelling/blob/ecc4ed93bb7f81ba28e3fb0acf46e66a79d18320/unknown-words.sh#L1857-L1875 to determine if a repository would need advanced security.

**Comment by woodruffw** [comment]
> [!WARNING]
> This action is not ready for general use yet! You can experiment with it, but please
> don't expect feature completeness or general readiness until a stable update is done.

Update: I've begun working on https://github.com/zizmorcore/zizmor-action for this!

It works similarly to the existing recommended workflow, i.e. you can define a workflow like so:

```yaml
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private repos
      actions: read # only needed for private repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@v0.0.1
```

...and that'll do the same thing, including GitHub "Advanced Security" integration via SARIF.
