### ISSUE TITLE
Feature: detect no-op conditions

### ISSUE THREAD

**Issue by woodruffw** [zizmorcore/zizmor#742]
This probably makes sense as an extension to the `obfuscation` audit, or perhaps as a new audit.

TL;DR: we should detect `if:` clauses that look like `if: ${{ expr }} != true` or similar. These clauses always evaluate to `true`, since GitHub evaluates `${{ expr }}` but not the `!=`, since it's outside of the expression. The result is the string literal `{eval} != true`, which then evaluates to `true` since it's a non-empty string.

More generally, any `if:` clause that looks like a curly expr preceded or followed by non-whitespace is a no-op. For example, all of these are no-ops that evaluate to `true`:

```yaml
if: true && ${{ false }} # => true
if: ${{ false }} && true # => true
if: ${{ false }} lol # => true
if: lol ${{ false }} # => true
```

We should only flag these in the context of `if:` and similar.
