### ISSUE TITLE
[BUG] False positive detection for artipacked when `persist-credentials: false` is properly set

### ISSUE THREAD

**Issue by woodruffw** [zizmorcore/zizmor#755]
### Discussed in https://github.com/woodruffw/zizmor/discussions/754

<div type='discussions-op-text'>

<sup>Originally posted by **dfabbie** May  6, 2025</sup>
Hello Zizmor community,
I've been integrating Zizmor into our GitHub Actions workflow to scan for security issues. I've encountered what appears to be false positive detection for the artipacked finding, and I'm hoping to understand if this is expected behavior or if I'm missing something.

Description
Zizmor flags files as missing `persist-credentials: false` even when that setting is properly included in the workflow file.
Here's a snippet from one of our workflow files:
```
yamlsteps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      persist-credentials: false
   ```   
However, Zizmor reports this as:
```
"ident": "artipacked",
"desc": "credential persistence through GitHub Actions artifacts",
"locations": [
  {
    "symbolic": {
      "key": {
        "Local": {
          "prefix": ".",
          "given_path": "./workflows/deploy.yaml"
        }
      },
      "annotation": "does not set persist-credentials: false",
      ...
    },
    "concrete": {
      "location": {
        "start_point": {
          "row": 19,
          "column": 8
        },
        "end_point": {
          "row": 20,
          "column": 33
        },
        ...
      },
      "feature": "name: Checkout\n        uses: actions/checkout@v4",
      ...
    }
  }
]
```

Based on the feature field and the location coordinates, it appears Zizmor is only analyzing the action `name` and `uses` lines, but not checking the` with:` block below it where `persist-credentials: false` is actually set.

Is this expected behavior, or is this a bug in Zizmor's detection logic?
Is there a way to configure Zizmor to check the entire step definition, including the `with:` block?
Are there any recommended approaches to handle these false positives?

I appreciate any insights or suggestions. 

Thank you!</div>

**Comment by woodruffw** [comment]
@dfabbie:

If possible, could you provide a full reproducer case instead of just a snippet? `zizmor` does indeed check the `with:` block for the `artipacked` audit, which you can see here: 

https://github.com/woodruffw/zizmor/blob/e63b72927e936079bc64d55bcf65f06e32aebd4b/src/audit/artipacked.rs#L68-L83

In other words, setting `persist-credentials: false` _should_ always work, but it's possible there's a bug or edge case in our detection. A full reproducer case would help me confirm this 🙂

**Comment by woodruffw** [comment]
For reference, here's my attempt to reproduce the report:

```yaml
# see https://github.com/woodruffw/zizmor/issues/755

name: ISSUE-755-REPRO
on: push

permissions: {}

jobs:
  issue-755-repro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
```

However this produces no findings, either on `1.6.0` or `main`:

```console
$ zizmor tests/integration/test-data/artipacked/issue-755-repro.yml
 
 INFO zizmor: skipping impostor-commit: can't run without a GitHub API token
 INFO zizmor: skipping ref-confusion: can't run without a GitHub API token
 INFO zizmor: skipping known-vulnerable-actions: can't run without a GitHub API token
 INFO zizmor: skipping forbidden-uses: audit not configured
 INFO audit: zizmor: 🌈 completed tests/integration/test-data/artipacked/issue-755-repro.yml
No findings to report. Good job!
```

**Comment by woodruffw** [comment]
@dfabbie Gentle ping for more information! I haven't been able to reproduce this so far.

**Comment by tylerjereddy** [comment]
@woodruffw you should be able to reproduce some false positives with `persist-credentials` based on the code/discussion at https://github.com/scipy/scipy/pull/22967.

**Comment by woodruffw** [comment]
@tylerjereddy I might be misunderstanding, but this seems like a different case: this bug is about `persist-credentials: false` not being honored (which I've been unable to repro), while https://github.com/scipy/scipy/pull/22967 is about `persist-credentials: false` being _superfluous_ when the job/workflow in question has `contents: read` as its sole permission.

Am I getting that right? If so I think you have indeed hit a bug here 🙂 -- if the job/workflow in question has `contents: read` as its only permission, then we should emit a pedantic-only finding here, rather than a default finding. But that's a distinct bug from the top-level report!

**Comment by dfabbie** [comment]
Hello @woodruffw,
Sorry for the late response. Here is ont part of the workflow:

```name: Update the Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project_name: fake-vm 
            manifests: |
              kubernetes/fake-vm
    name: Deploy to Cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false```

and here is what zizmor outputs:

```{
  "ident": "artipacked",
  "desc": "credential persistence through GitHub Actions artifacts",
  "locations": [
    {
      "symbolic": {
        "key": {
          "Local": {
            "given_path": "./.github/workflows/kubernetes-deploy.yaml"
          }
        },
        "annotation": "does not set persist-credentials: false"
      },
      "concrete": {
        "location": {
          "start_point": {
            "row": 19,
            "column": 8
          },
          "end_point": {
            "row": 20,
            "column": 33
          }
        },
        "feature": "name: Checkout\n        uses: actions/checkout@v4"
      }
    }
  ]
}```

Please let me know if you need anything else

**Comment by woodruffw** [comment]
No problem at all @dfabbie! Thanks for the example; I'll attempt to repro tonight.

**Comment by woodruffw** [comment]
Hey @dfabbie, unfortunately I still wasn't able to reproduce this. Here's the input I'm using, based on yours:

```yaml
# see https://github.com/woodruffw/zizmor/issues/755

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project_name: fake-vm
            manifests: |
              kubernetes/fake-vm
    name: Deploy to Cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
```

...and here's what I get when I run `zizmor`:

```
 INFO zizmor: skipping impostor-commit: can't run without a GitHub API token
 INFO zizmor: skipping ref-confusion: can't run without a GitHub API token
 INFO zizmor: skipping known-vulnerable-actions: can't run without a GitHub API token
 INFO zizmor: skipping forbidden-uses: audit not configured
 INFO zizmor: skipping stale-action-refs: can't run without a GitHub API token
 INFO audit: zizmor: 🌈 completed tests/integration/test-data/artipacked/issue-755-repro.yml
warning[excessive-permissions]: overly broad permissions
  --> tests/integration/test-data/artipacked/issue-755-repro.yml:9:3
   |
 9 | /   deploy:
10 | |     runs-on: ubuntu-latest
...  |
21 | |         with:
22 | |           persist-credentials: false
   | |                                     -
   | |_____________________________________|
   |                                       this job
   |                                       default permissions used due to no permissions: block
   |
   = note: audit confidence → Medium

2 findings (1 suppressed): 0 unknown, 0 informational, 0 low, 1 medium, 0 high
```

So I get an `excessive-permissions` finding, but not an `artipacked` one. 

Is there any more information you can provide here? I'm wondering if you're accidentally hitting https://github.com/zizmorcore/zizmor/issues/290 -- can you confirm that you have a `with:` block?
