### ISSUE TITLE
New audit: comments next to explicit permissions

### ISSUE THREAD

**Issue by woodruffw** [zizmorcore/zizmor#819]
This would be a good pedantic/auditor-only (probably the latter) audit: when a workflow/job has a `permissions:` block, each explicit permission in that block should have an explanatory comment.

For example, this should flag the first permission but not the second:

```yaml
permissions:
  contents: write
  id-token: write # for frobulating
```
