### ISSUE TITLE
[BUG]: Zizmor breaks when using GitHubSecurityLab/actions-permissions/monitor

### ISSUE THREAD

**Issue by jacobwoffenden** [zizmorcore/zizmor#853]
### Pre-submission checks

- [x] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [x] I have looked through the [open issues](https://github.com/zizmorcore/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### zizmor version

1.8.0

### Expected behavior

I expected Zizmor to work when using in conjunction with [`GitHubSecurityLab/actions-permissions/monitor`](https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor)

### Actual behavior

Fails with:

```
× Failed to fetch: `[https://pypi.org/simple/zizmor/`](https://pypi.org/simple/zizmor/%60)
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://pypi.org/simple/zizmor/)
  ├─▶ client error (Connect)
  ╰─▶ invalid peer certificate: UnknownIssuer
  help: Consider enabling use of system TLS certificates with the
        `--native-tls` command-line flag
```

### Reproduction steps

Use this workflow:

```yaml
---
name: 🌈 Zizmor

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Monitor GitHub Actions Permissions
        id: monitor_permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@31cf7361439cbdffbc73a3bb138b7e1662d46c9b # v1.0.2-beta6

      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install uv
        id: install_uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0

      - name: Zizmor
        id: run_zizmor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uvx zizmor --format sarif . > zizmor.sarif

      - name: Upload SARIF
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: zizmor.sarif
          category: zizmor

```

### Logs

```plain text
Unable to reproduce locally
```
