### ISSUE TITLE
[BUG]: auto fix for `template-injection` removes comments from `env` block

### ISSUE THREAD

**Issue by gforsyth** [zizmorcore/zizmor#992]
### Pre-submission checks

- [x] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [x] I have looked through the [open issues](https://github.com/zizmorcore/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### zizmor version

1.10.0

### Expected behavior

Hi!  `zizmor` is great, and this is a non-critical bug, just an annoyance.

When `zizmor` autofixes a `template-injection` error by adding an additional entry to the `env`, it deletes any existing comments that were already in place in the `env` block:

Here's an injection-vulnerable step:

```yaml
    - name: Needs a redirection
      run: ${{ inputs.script }}
      env:
        # An existing comment about this wacky env-var
        WACKY: "It's just a wacky world"
```

`zizmor` flags this, and can autofix it. 

I'd expect to get out something like:

```yaml
    - name: Needs a redirection
      run: ${INPUTS_SCRIPT}
      env:
        # An existing comment about this wacky env-var
        WACKY: "It's just a wacky world"
        INPUTS_SCRIPT: ${{ inputs.script }}
```

### Actual behavior

The output of `zizmor --fix=all` on the above snippet is

```yaml
    - name: Needs a redirection
      run: ${INPUTS_SCRIPT}
      env:
        WACKY: It's just a wacky world
        INPUTS_SCRIPT: ${{ inputs.script }}
```

### Reproduction steps

Stick this snippet into a file:

```yaml
    - name: Needs a redirection
      run: ${{ inputs.script }}
      env:
        # An existing comment about this wacky env-var
        WACKY: "It's just a wacky world"
```

Then run `zizmor --fix=all` on that file

### Logs

```plain text

```
